CREATE TABLE IF NOT EXISTS users (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  display_name TEXT DEFAULT NULL,
  avatar TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS threads (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  author INTEGER REFERENCES users(id) NOT NULL,
  is_pinned BOOLEAN DEFAULT false NOT NULL,
  locked BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  thread INTEGER REFERENCES threads(id) NOT NULL,
  author INTEGER REFERENCES users(id) NOT NULL,
  locked BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_edited BOOLEAN DEFAULT false NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  post INTEGER REFERENCES posts(id) NOT NULL,
  author INTEGER REFERENCES users(id) NOT NULL,
  reference INTEGER REFERENCES comments(id) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_edited BOOLEAN DEFAULT false NOT NULL,
  body TEXT NOT NULL
);

INSERT INTO users (username, password)
  VALUES ('system', '');